// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar'];
    ABadge: typeof import('@arco-design/web-vue')['Badge'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    ACheckboxGroup: typeof import('@arco-design/web-vue')['CheckboxGroup'];
    ACol: typeof import('@arco-design/web-vue')['Col'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADivider: typeof import('@arco-design/web-vue')['Divider'];
    ADoption: typeof import('@arco-design/web-vue')['Doption'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown'];
    AEmpty: typeof import('@arco-design/web-vue')['Empty'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AImage: typeof import('@arco-design/web-vue')['Image'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    ALayout: typeof import('@arco-design/web-vue')['Layout'];
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    AModal: typeof import('@arco-design/web-vue')['Modal'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    APopover: typeof import('@arco-design/web-vue')['Popover'];
    ARadio: typeof import('@arco-design/web-vue')['Radio'];
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup'];
    AResult: typeof import('@arco-design/web-vue')['Result'];
    ARow: typeof import('@arco-design/web-vue')['Row'];
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASlider: typeof import('@arco-design/web-vue')['Slider'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATabPane: typeof import('@arco-design/web-vue')['TabPane'];
    ATabs: typeof import('@arco-design/web-vue')['Tabs'];
    ATag: typeof import('@arco-design/web-vue')['Tag'];
    ATextarea: typeof import('@arco-design/web-vue')['Textarea'];
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip'];
    ATypography: typeof import('@arco-design/web-vue')['Typography'];
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText'];
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle'];
    AUpload: typeof import('@arco-design/web-vue')['Upload'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
