// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    ACol: typeof import('@arco-design/web-vue')['Col'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker'];
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions'];
    ADescriptionsItem: typeof import('@arco-design/web-vue')['DescriptionsItem'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    AEmpty: typeof import('@arco-design/web-vue')['Empty'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AImage: typeof import('@arco-design/web-vue')['Image'];
    AImagePreview: typeof import('@arco-design/web-vue')['ImagePreview'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    AModal: typeof import('@arco-design/web-vue')['Modal'];
    AMonthPicker: typeof import('@arco-design/web-vue')['MonthPicker'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader'];
    APagination: typeof import('@arco-design/web-vue')['Pagination'];
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm'];
    AProgress: typeof import('@arco-design/web-vue')['Progress'];
    ARadio: typeof import('@arco-design/web-vue')['Radio'];
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup'];
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker'];
    AResult: typeof import('@arco-design/web-vue')['Result'];
    ARow: typeof import('@arco-design/web-vue')['Row'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn'];
    ATabPane: typeof import('@arco-design/web-vue')['TabPane'];
    ATabs: typeof import('@arco-design/web-vue')['Tabs'];
    ATag: typeof import('@arco-design/web-vue')['Tag'];
    ATextarea: typeof import('@arco-design/web-vue')['Textarea'];
    ATimePicker: typeof import('@arco-design/web-vue')['TimePicker'];
    ATree: typeof import('@arco-design/web-vue')['Tree'];
    ATreeSelect: typeof import('@arco-design/web-vue')['TreeSelect'];
    AUpload: typeof import('@arco-design/web-vue')['Upload'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
